export const FETCH_API_HOME_SLIDE = "FETCH_API_HOME_SLIDE";
export const FETCH_API_HOME_SLIDE_SUCCESS = "FETCH_API_HOME_SLIDE_SUCCESS";
export const FETCH_API_HOME_SLIDE_ERR = "FETCH_API_HOME_SLIDE_ERR";

export const FETCH_API_HOME_PRODUCTS = "FETCH_API_HOME_PRODUCTS";
export const FETCH_API_HOME_PRODUCTS_SUCCESS =
  "FETCH_API_HOME_PRODUCTS_SUCCESS";
export const FETCH_API_HOME_PRODUCTS_ERR = "FETCH_API_HOME_PRODUCTS_ERR";

export const FETCH_API_SHOES_MEN = "FETCH_API_SHOES_MEN";
export const FETCH_API_SHOES_MEN_SUCCESS = "FETCH_API_SHOES_MEN_SUCCESS";
export const FETCH_API_SHOES_MEN_ERR = "FETCH_API_SHOES_MEN_ERR";

export const FETCH_API_SHOES_WOMON = "FETCH_API_SHOES_WOMON";
export const FETCH_API_SHOES_WOMON_SUCCESS = "FETCH_API_SHOES_WOMON_SUCCESS";
export const FETCH_API_SHOES_WOMON_ERR = "FETCH_API_SHOES_WOMON_ERR";

export const FETCH_API_SHOES_SPORT = "FETCH_API_SHOES_SPORT";
export const FETCH_API_SHOES_SPORT_SUCCESS = "FETCH_API_SHOES_SPORT_SUCCESS";
export const FETCH_API_SHOES_SPORT_ERR = "FETCH_API_SHOES_SPORT_ERR";

export const FETCH_API_SEARCH_PRODUCTS = "FETCH_API_SEARCH_PRODUCTS";
export const FETCH_API_SEARCH_PRODUCTS_SUCCESS =
  "FETCH_API_SEARCH_PRODUCTS_SUCCESS";
export const FETCH_API_SEARCH_PRODUCTS_ERR =
  "FETCH_APFETCH_API_SEARCH_PRODUCTS_ERRI_SEARCH_PRODUCTS";

export const FETCH_API_NIKE_PAGE = "FETCH_API_NIKE_PAGE";
export const FETCH_API_NIKE_PAGE_SUCCESS = "FETCH_API_NIKE_AGE_SUCCESS";
export const FETCH_API_NIKE_PAGE_ERR = "FETCH_API_NIKE_PAGE_ERR";

export const FETCH_API_ADIDAS_PAGE = "FETCH_API_ADIDAS_PAGE";
export const FETCH_API_ADIDAS_PAGE_SUCCESS = "FETCH_API_ADIDAS_PAGE_SUCCESS";
export const FETCH_API_ADIDAS_PAGE_ERR = "FETCH_API_ADIDAS_PAGE_ERR";
