export const TOGGLE_MENU_BAR = "TOGGLE_MENU_BAR";
export const SHOW_MENU_MOBILE = "SHOW_MENU_MOBILE";
export const CLOSE_MENU_MOBILE = "CLOSE_MENU_MOBILE";

export const OPEN_SEARCH_MOBILE = "OPEN_SEARCH_MOBILE";
export const CLOSE_SEARCH_MOBILE = "CLOSE_SEARCH_MOBILE";
