export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_ERR = "ADD_TO_CART_ERR";

export const UPDATE_TO_CART = "UPDATE_TO_CART";
export const UPDATE_TO_CART_SUCCESS = "UPDATE_TO_CART_SUCCESS";
export const UPDATE_TO_CART_ERR = "UPDATE_TO_CART_ERR";

export const DELETE_PRODUCTS_CART = "DELETE_PRODUCTS_CART";
export const DELETE_PRODUCTS_CART_SUCCESS = "DELETE_PRODUCTS_CART_SUCCESS";
export const DELETE_PRODUCTS_CART_ERR = "DELETE_PRODUCTS_CART_ERR";
